# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  #default:
  branches:
    # master:
    # - step:
        # services:
          # - docker
        # script: # Modify the commands below to build your repository.
          # # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          # - export IMAGE_NAME=k1fathi33/gameon:$BITBUCKET_COMMIT
          # # build the Docker image (this will use the Dockerfile in the root of the repo)
          # - docker build -t $IMAGE_NAME .
          # # authenticate with the Docker Hub registry
          # - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # # push the new Docker image to the Docker registry
          # - docker push $IMAGE_NAME
    development:
      # - step:
            # caches:
              # - composer
            # script:
              # - apt-get update && apt-get install -y unzip
              # - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              # - composer install --no-dev
      - step:
             name: Deploy to production
             deployment: production
             script:
               - pipe: atlassian/ssh-run:0.2.2
                 variables:
                   SSH_USER: root
                   SERVER: 178.128.68.183
                   COMMAND: ./bin/deploygameon
                   #SSH_KEY: $my_ssh_key

definitions:
  services:
    docker:
      memory: 2048
    #mysql:
    #      image: mysql:5.7
    #      environment:
    #        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    #        MYSQL_DATABASE: 'homestead'
    #        MYSQL_USER: 'homestead'
    #        MYSQL_PASSWORD: 'secret'